### ISSUE TITLE
No where to find the encoder.

### ISSUE THREAD

**Issue by LITTOMA** [Gericom/FastVideoDSPlayer#1]
Only one simple guide found [here](https://wiki.ds-homebrew.com/ds-index/videoplayers).

**Comment by spellboundtriangle** [comment]
The encoder is pinned in DSi Mode Hacking's #fastvideods. It hasn't been uploaded on GitHub yet because Gericom hasn't deemed it ready

**Comment by Gericom** [comment]
It will soon be available on GitHub. The code still needed some cleaning up before I wanted to publish it.
